-- Stepin2Green — volunteer rows exported from Railway MySQL
-- 28 rows, ids 7–34
--
-- Run this AFTER 00-schema.sql. Table names are fully qualified so it works
-- whichever database the SQL Editor has selected — there is no USE statement,
-- because the web editor runs one statement at a time and USE does not carry
-- over between runs.
--
-- The TiDB SQL Editor runs the statement your CURSOR is in, not the whole
-- file. Run the three statements below one at a time: click inside each, then
-- press Run.
--
-- Timestamps are UTC, matching the schema.

INSERT INTO stepin2green.volunteers
  (id, full_name, email, instagram, background, team, message, submitted_at)
VALUES
  (7, 'Avryl Doh Ai Qi', 'avrylldohhh@gmail.com', NULL, 'no', 'Media', 'Idk', '2026-08-02 05:04:06'),
  (8, 'a', 'avaneshlm8@gmail.com', NULL, 'no', 'Research', 'i love ariana grande', '2026-08-02 05:11:53'),
  (9, 'a', 'avaneshlm8@gmail.com', NULL, 'no', 'Research', 'i love ariana grande', '2026-08-02 05:11:54'),
  (10, 'BABAAVAAAV', 'baavhanashri09@gmail.com', NULL, 'Goon', 'Creative', 'HSURUP', '2026-08-02 05:34:25'),
  (11, 'Joel', 'mrcheese9600@gmail.com', NULL, 'Test', 'Outreach', 'Test', '2026-08-02 18:38:40'),
  (12, 'Chelsea Wang', 'chelsea.wang918@outlook.com', NULL, 'Veterinary medicine student and artist', 'Creative', 'I''m a vet med student who is very passionate about the environment! I also love making art, and almost all my art projects are focused on wildlife or their environment in some way. I''d love to contribute to a project like this and spread awareness and interests to the general public through art and research!', '2026-08-02 22:08:24'),
  (13, 'Joel', 'mrcheese9600@gmail.com', NULL, 'Test', 'Outreach', 'Test', '2026-08-03 19:51:48'),
  (14, 'Chiara Milesi', 'chrmilesi@gmail.com', NULL, 'Illustration artist', 'Creative', 'I''m an illustration artist who love nature, outdoor life.... And drawing about them of course!', '2026-08-04 21:35:03'),
  (15, 'Najah Najwa binti Masri', 'najahnajwa3@gmail.com', NULL, 'I''m currently pursuing a Master''s in Environmental Assessment and Monitoring at Universiti Kebangsaan Malaysia (UKM). I completed my Bachelor''s degree in Biology and previously worked as a nutritionist in a pharmacy. I have a strong interest in the environment and enjoy learning about nature, environmental conservation, and sustainability. I also enjoy learning new things, working with people, and taking on new challenges that help me grow both personally and professionally.', 'Outreach', 'I want to be part of team that have positive outcome, also i want to gain experience and skills. I want to contribute my energy and time with something valuable to community.', '2026-08-05 07:23:14'),
  (16, 'Bronwyn Dinh', 'bronwyndinh@gmail.com', NULL, 'Graphic Designer & Illustrator', 'Creative', 'I’m passionate about creating abstract, colourful and expressive illustrations. I also really care about the environment and being sustainable. Your post calling for applications resonates with me, particularly since I have one illustration suite project that focused on the ACF (Australian Conservation Foundation) — you can check it out on my Instagram (@bronzwyng)! Nonetheless, I’m always eager for any opportunity to be artistically active, as well as to expand my skills on various creative mediums.', '2026-08-06 09:26:31'),
  (17, 'Mirah', 'mirahwaseem91@gmail.com', NULL, 'Biology', 'Research', 'I want to volunteer to gain real-world experience and give back to my community. My time at an ENT clinic gave me my first exposure to patient care, where I observed doctors diagnosing ear, nose, and throat conditions and learned about treatment, hygiene, and patient interaction. I also assisted with patient records and clinic organization, which taught me responsibility and teamwork. That experience made biology and anatomy feel real instead of just textbook concepts. Volunteering will help me improve my communication skills, understand hospital workflow, and deepen my scientific knowledge by seeing how diseases, medicines, and the human body actually work. I’m eager to learn from healthcare professionals and grow in both science and service.', '2026-08-10 02:44:09'),
  (18, 'BAAAVVV', 'baavhqnaehrir@agam', NULL, 'Avryl', 'Creative', 'So like', '2026-08-11 03:08:20'),
  (19, 'Brayden Quan', 'kangaboy436@gmail.com', NULL, 'Biology student, Photography, Video Editing, Flowers, Birds', 'Media', 'As a person who has experiences in hong kong, I am always face-to-face with quite severe pollution in the suburbs. I believe that we can make differenece using the help of social media and determination. I love the enviroment around me and I will do what it takes to protect it. With my help, I will do my best to catch all eyes with our videos and posts. I do hope you will accept my application form. If you do require anything, please contact me by email or instagram. Thank you', '2026-08-11 06:02:33'),
  (20, 'George Moromoke Ugochukwu', 'Moromoke057@gmail.com', NULL, 'Nursing', 'Research', 'I want to give back to the Society, I love researching and I want to deepen my knowledge in the health field', '2026-08-11 12:03:09'),
  (21, 'Hannah Clark', 'hannahaclark11@icloud.com', '@_hannahacarchives', 'Artist, Communications, English and Writing', 'Creative', 'I have a bachelors degree in English and Communications and a very strong passion for art. On the side, I run social media for a small business which I enjoy creating graphics and content for. I love the outdoors and keeping fit, and would absolutely love to use my skills to help with something I love! I look forward to hearing from you.', '2026-08-11 18:51:36'),
  (22, 'Hannah Clark', 'hannahaclark11@icloud.com', '@_hannahacarchives', 'Artist, Communications, English and Writing', 'Creative', 'I have a bachelors degree in English and Communications and a very strong passion for art. On the side, I run social media for a small business which I enjoy creating graphics and content for. I love the outdoors and keeping fit, and would absolutely love to use my skills to help with something I love! I look forward to hearing from you.', '2026-08-11 18:51:36'),
  (23, 'Hannah Clark', 'hannahaclark11@icloud.com', '@_hannahacarchives', 'Artist, Communications, English and Writing', 'Creative', 'I have a bachelors degree in English and Communications and a very strong passion for art. On the side, I run social media for a small business which I enjoy creating graphics and content for. I love the outdoors and keeping fit, and would absolutely love to use my skills to help with something I love! I look forward to hearing from you.', '2026-08-11 18:53:09'),
  (24, 'Keshav Karthik', 'kshavkarthik@gmail.com', '@kingofdinosaurs2701', 'Biology student, zoology and botany specialist', 'Research', 'I am eager to volunteer because I want to bridge the gap between environmental passion and data-driven solutions. My background has equipped me with strong research, data analysis, and critical thinking skills. I am highly motivated to contribute to your team''s fieldwork and data collection efforts. This role allows me to directly support evidence-based conservation while expanding my scientific research experience. "I want to leverage my analytical skills to advance your nature conservation initiatives. I specialize in literature reviews, methodology design, and synthesizing complex environmental data into actionable insights. Volunteering with your organization offers the perfect opportunity to apply my academic training to real-world ecological challenges. I am committed to maintaining high scientific integrity in supporting your ongoing research projects.', '2026-08-14 04:34:28'),
  (25, 'Keshav Karthik', 'kshavkarthik@gmail.com', '@kingofdinosaurs2701', 'Biology student, zoology and botany specialist', 'Research', 'I am eager to volunteer because I want to bridge the gap between environmental passion and data-driven solutions. My background has equipped me with strong research, data analysis, and critical thinking skills. I am highly motivated to contribute to your team''s fieldwork and data collection efforts. This role allows me to directly support evidence-based conservation while expanding my scientific research experience. "I want to leverage my analytical skills to advance your nature conservation initiatives. I specialize in literature reviews, methodology design, and synthesizing complex environmental data into actionable insights. Volunteering with your organization offers the perfect opportunity to apply my academic training to real-world ecological challenges. I am committed to maintaining high scientific integrity in supporting your ongoing research projects.', '2026-08-14 04:35:00'),
  (26, '🤨', 'ykang6683@gmail.com', '@kainasai_', 'None', 'Media', 'Cause I can🤫🤫', '2026-08-15 03:24:42'),
  (27, '🤫', 'yk6683@outlook.com', '@kainasai_', 'None', 'Media', 'I volunteer can I can 🤫🤫🤫', '2026-08-15 03:26:13'),
  (28, '🤫', 'yk6683@outlook.com', '@kainasai_', 'None', 'Media', 'I volunteer can I can 🤫🤫🤫', '2026-08-15 03:27:39'),
  (29, '🤫', 'yk6683@outlook.com', '@kainasai_', 'None', 'Media', 'I volunteer can I can 🤫🤫🤫', '2026-08-15 03:27:40'),
  (30, '🤫', 'yk6683@outlook.com', '@kainasai_', 'None', 'Media', 'I volunteer can I can 🤫🤫🤫', '2026-08-15 03:27:41'),
  (31, 'Rowan Naththarampatha', 'rowannath26@gmail.com', 'rowannn.n', 'Environmental Student / Geology, Art, Nature', 'Research', 'I want to volunteer to gain valuable experience and insights that will strengthen my portfolio and own knowledge, as well as working towards making a difference in the way science is viewed and engaged with by the general public. I have loved science since I was a kid, and I have experience in volunteering on small nature reserves. I am competent in research and written communication skills.', '2026-08-16 19:53:40'),
  (32, 'Rowan Naththarampatha', 'rowannath26@gmail.com', 'rowannn.n', 'Environmental Student / Geology, Art, Nature', 'Research', 'I want to volunteer to gain valuable experience and insights that will strengthen my portfolio and own knowledge, as well as working towards making a difference in the way science is viewed and engaged with by the general public. I have loved science since I was a kid, and I have experience in volunteering on small nature reserves. I am competent in research and written communication skills.', '2026-08-16 19:54:14'),
  (33, 'Rowan Naththarampatha', 'rowannath26@gmail.com', 'rowannn.n', 'Environmental Student / Geology, Art, Nature', 'Research', 'I want to volunteer to gain valuable experience and insights that will strengthen my portfolio and own knowledge, as well as working towards making a difference in the way science is viewed and engaged with by the general public. I have loved science since I was a kid, and I have experience in volunteering on small nature reserves. I am competent in research and written communication skills.', '2026-08-16 19:55:03'),
  (34, 'Jayden Lee Enjoe', 'jaydenleeenjoe@gmail.com', '@singe5021', NULL, 'Media', NULL, '2026-08-18 18:54:32');

-- Make sure new submissions start after the highest imported id.
ALTER TABLE stepin2green.volunteers AUTO_INCREMENT = 35;

-- Sanity check — should return 28
SELECT COUNT(*) AS imported FROM stepin2green.volunteers;
